version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: diary-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: 'diary'
    ports:
      - '3306:3306'
    volumes:
      - ./data/mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password